import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import clsx from "clsx";
const buttonClass = "rounded-xl px-4 py-3 font-semibold transition-colors text-sm";
export function Controls({ rolloutState, cooldownSeconds, onPromote, onPause, onResume, onRollback, actions, busy = false, }) {
    const showResume = rolloutState === "paused";
    const promoteDisabled = actions.promote.disabled || busy;
    const pauseDisabled = actions.pause.disabled || busy;
    const resumeDisabled = actions.resume.disabled || busy;
    const rollbackDisabled = actions.rollback.disabled || busy;
    return (_jsxs("div", { className: "space-y-3 rounded-2xl border border-white/5 bg-slate-900/60 p-4 shadow-inner", children: [_jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsx("button", { type: "button", className: clsx(buttonClass, "bg-emerald-500/90 text-black hover:bg-emerald-400", (promoteDisabled || busy) && "pointer-events-none opacity-50"), onClick: onPromote, disabled: promoteDisabled, title: busy ? "Action running…" : actions.promote.reason ?? undefined, "aria-disabled": promoteDisabled, children: "Promote" }), _jsx("button", { type: "button", className: clsx(buttonClass, "bg-yellow-500/80 text-black hover:bg-yellow-400", (pauseDisabled || busy) && "pointer-events-none opacity-50"), onClick: onPause, disabled: pauseDisabled, title: busy ? "Action running…" : actions.pause.reason ?? undefined, "aria-disabled": pauseDisabled, children: "Pause" }), showResume && (_jsx("button", { type: "button", className: clsx(buttonClass, "bg-sky-500/80 text-black hover:bg-sky-400", (resumeDisabled || busy) && "pointer-events-none opacity-50"), onClick: onResume, disabled: resumeDisabled, title: busy ? "Action running…" : actions.resume.reason ?? undefined, "aria-disabled": resumeDisabled, children: "Resume" })), _jsx("button", { type: "button", className: clsx(buttonClass, "bg-rose-500/80 text-black hover:bg-rose-400", (rollbackDisabled || busy) && "pointer-events-none opacity-50"), onClick: onRollback, disabled: rollbackDisabled, title: busy ? "Action running…" : actions.rollback.reason ?? undefined, "aria-disabled": rollbackDisabled, children: "Rollback" })] }), cooldownSeconds > 0 && (_jsxs("p", { className: "text-sm text-slate-300", children: ["Cooldown: next promotion allowed in", " ", _jsxs("strong", { children: [cooldownSeconds, "s"] })] })), showResume && (_jsx("p", { className: "text-xs text-slate-400", children: "Resume re-evaluates the rollout and dispatches a promotion request to continue the rollout." }))] }));
}
